var preguntas = [
  {
    q: "¿En qué año se estrenó la primera película de Iron Man, que lanzó el Marvel Cinematic Universe?",
    o1: "2005",
    o2: "2008",
    o3: "2010",
    o4: "2012",
    ac: "2008",
  },
  {
    q: "¿Cómo se llama el martillo de Thor?",
    o1: "Vanir",
    o2: "Mjolnir",
    o3: "Aesir",
    o4: "Norn",
    ac: "Mjolnir",
  },
{
    q:"En The Incredible Hulk, ¿qué le dice Tony a Thaddeus Ross al final de la película?",
    o1:"Que quiere estudiar The Hulk",
    o2:"Que él sabe sobre SHIELD",
    o3:"Que están formando un equipo",
    o4:"Que Thaddeus le debe dinero",
    ac:"Que están formando un equipo",
},
{
    q:"¿De qué está hecho el escudo del Capitán América?",
    o1:"Adamantium",
    o2:"Vibranio",
    o3:"Prometeo",
    o4:"Carbonadio",
    ac:"Vibranio",
},
{
    q: "Los Flerkens son una raza de alienígenas extremadamente peligrosos que se parece a qué.",
    o1:"Gatos",
    o2:"Patos ",
    o3:"Reptiles ",
    o4:"Mapaches ",
    ac:"Gatos",
},
{
    q: "Antes de convertirse en Visión, ¿cómo se llama el mayordomo de inteligencia artificial de Iron Man?",
    o1:"Homero",
    o2:"Jarvis",
    o3:"Alfred",
    o4:"Marvin",
    ac:"Jarvis",
},
{
    q: "¿Cuál es el verdadero nombre de la Pantera Negra?",
    o1:"T'Challa",
    o2:"M'Baku",
    o3:"N'Jadaka",
    o4:"N'Jobu",
    ac:"T'Challa",
},
{
    q: "¿Cuál es la raza alienígena que Loki envía para invadir la Tierra en The Avengers?",
    o1:"El chitauri",
    o2:"Los skrulls",
    o3:"El kree",
    o4:"Los flerkens",
    ac:"El chitauri",
},
{
    q: "¿Quién fue el último titular de la Piedra espacial antes de que Thanos lo reclame por su Infinity Gauntlet?",
    o1:"Thor",
    o2:"Loki",
    o3:"El coleccionista",
    o4:"Tony Stark",
    ac:"Loki",
},
{
    q: "¿Qué nombre falso usa Natasha cuando conoce a Tony por primera vez?",
    o1:"Natalie Rushman",
    o2:"Natalia Romanoff",
    o3:"Nicole Rohan",
    o4:"Naya Rrabe",
    ac:"Natalie Rushman",
},
{
    q: "¿De qué quiere Thor otro cuando está en el restaurante?",
    o1:"Un trozo de tarta",
    o2:"Una pinta de cerveza",
    o3:"Una pila de panqueques",
    o4:"Una taza de café",
    ac:"Una taza de café",
},
{
    q: "¿Dónde le dice Peggy a Steve que quiere encontrarse con él para bailar, antes de que él se hunda en el hielo?",
    o1:"El Cotton Club",
    o2:"El Stork Club",
    o3:"El Marruecos",
    o4:"El Copacabana",
    ac:"El Stork Club",
},
{
    q: "¿Sobre qué ciudad recuerdan a menudo Hawkeye y Black Widow?",
    o1:"Budapest",
    o2:"Praga",
    o3:"Estanbul",
    o4:"Paris",
    ac:"Budapest",
},
{
    q: "¿A quién sacrifica el Titán Loco para adquirir la Piedra del Alma?",
    o1:"Nebula",
    o2:"Fauces de ébano",
    o3:"Obsidiana de sacrificio",
    o4:"Gamora",
    ac:"Gamora",
},
{
    q: "¿Cuál es el nombre del niño que Tony se hace amigo mientras está varado en Iron Man 3?",
    o1:"Harry",
    o2:"Enrique",
    o3:"Harley",
    o4:"Holden",
    ac:"Harley",
},
];